[package]
name    = "phonenumber"
version = "0.3.1+8.12.9"
edition = "2018"

authors = ["meh. <meh@1aim.com>"]
license = "Apache-2.0"

description = "Library for parsing, formatting and validating international phone numbers."
repository  = "https://github.com/1aim/rust-phonenumber"
keywords    = ["phonenumber", "phone", "number", "parser", "formatter"]
readme = "README.md"

[dependencies]
regex       = "1.3.9"
regex-cache = "0.2"
lazy_static = "1.4.0"
fnv         = "1.0"
thiserror   = "1.0.20"
quick-xml   = "0.22"
itertools   = "0.9.0"
either      = "1.6.0"
nom         = "5"

serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.3.1"

[build-dependencies]
quick-xml    = "0.22"
thiserror    = "1.0.20"
regex        = "1.3.9"
serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.3.1"

[dev-dependencies]
doc-comment  = "0.3"
